# Generated by Django 4.1.2 on 2022-10-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_title', models.CharField(max_length=25)),
                ('size', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('total_bill', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=25)),
                ('cat_description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='customer_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_product_title', models.CharField(max_length=25)),
                ('c_product_image', models.ImageField(upload_to='')),
                ('c_product_cost', models.FloatField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='log_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('user_password', models.CharField(max_length=25)),
                ('user_email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=25)),
                ('user_id', models.IntegerField()),
                ('user_contact', models.IntegerField()),
                ('address', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=25)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_price', models.FloatField()),
                ('cat_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
